Routing header/footer
Drews13/Lab_vue-1 pull request #1
Opened 2021-11-29 14:18 UTC by Drews13

2021-11-29 14:48 UTC, derkach-artem requested changes

2021-11-29 14:48 UTC, derkach-artem commented on public/css/main.css
> +body{
Для чего создан этот файл и зачем выносить все стили в глобальные?

2021-11-29 14:48 UTC, derkach-artem commented on public/css/main.css
> +#header {
Использовать селекторы тега и id - плохая идея

2021-11-29 14:48 UTC, derkach-artem commented on src/App.vue
> +import TheHeader from '@/components/TheHeader.vue';
В названии компонента не нужно указывать артикль `the`
Пример - VHeader, HederComponent,

2021-11-29 14:48 UTC, derkach-artem commented on src/components/TheFooterIcons.vue
> +    <section class = "icons">
Лишние пробелы нужно убрать

2021-11-29 14:48 UTC, derkach-artem commented on src/components/TheFooterIcons.vue
> +    <section class = "icons">
Класс нужно называть так что бы было понятно что это такое, а не просто `icons`. 
И желательно чтобы главный блок совпадал с названием компонента

2021-11-29 14:48 UTC, derkach-artem commented on src/views/404NotFound.vue
> +<template>
Класс называется NotFound, a название файла 404NotFound -  нужно привести к единому виду

2021-11-29 14:48 UTC, derkach-artem commented on src/views/AboutPage.vue
> +<template>
Тут название файла и название класса уже совпадают, но в стилях почему-то класс body

2021-11-29 14:48 UTC, derkach-artem commented on src/views/HomePage.vue
> +<template>
А тут вообе класса нет )))

2021-12-02 15:42 UTC, Drews13 commented on public/css/main.css
> +body{
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on public/css/main.css
> +#header {
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on src/App.vue
> +import TheHeader from '@/components/TheHeader.vue';
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on src/components/TheFooterIcons.vue
> +    <section class = "icons">
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on src/views/404NotFound.vue
> +<template>
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on src/views/AboutPage.vue
> +<template>
Исправлено

2021-12-02 15:42 UTC, Drews13 commented on src/views/HomePage.vue
> +<template>
Исправлено

2021-12-03 10:49 UTC, derkach-artem requested changes

2021-12-03 10:49 UTC, derkach-artem commented on src/assets/colors.scss
> +$color-white: #FFF;
Добавить пустую строку

2021-12-03 10:49 UTC, derkach-artem commented on src/assets/main-styles.scss
> +}
Добавить пустую строку

2021-12-03 10:49 UTC, derkach-artem commented on src/components/FooterComponentIcons.vue
> +  }
.footer-component {
   &__icons {}
   
   &__icons-list {}
   
   &-list-items {}
   
   &__icons-link {
      &:hover,
      &:focus {}
   }
}

2021-12-03 11:37 UTC, Drews13 commented on src/components/FooterComponentIcons.vue
> +  }
Исправил

2021-12-03 11:38 UTC, Drews13 commented on src/assets/colors.scss
> +$color-white: #FFF;
Исправил

2021-12-03 11:38 UTC, Drews13 commented on src/assets/main-styles.scss
> +}
Исправил

2021-12-03 11:44 UTC, derkach-artem approved these changes

2021-12-03 11:52 UTC, merged